name: Compate functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}
          STARTS_WITH_FUNC: ${{ startsWith('Hello', 'He') }}
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'lo') }}
      - run: echo "${{ contains(github.event.issue.labels.*.name, 'bug') }}"
      - run: echo "${{ github.event.issue.labels }}"
