name: Concurrency
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 131
      - run: exit 0
      - run: exit 1
