name: Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "actor ${{ github.actor }}"
      - run: echo "run_id ${{ github.run_id }}"
      - run: echo "head_ref ${{ github.head_ref }}"
      - run: echo "workspace ${{ github.workspace }}"
      - run: echo "repository ${{ github.repository }} "
      - run: echo "repository_owner ${{ github.repository_owner }}"
      - run: echo "event ${{ github.event }}"
