name: Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "actor ${{ github.actor }}"
      - run: echo "run_id ${{ github.run_id }}"
      - run: echo "head_ref ${{ github.head_ref }}"
      - run: echo "workspace ${{ github.workspace }}"
      - run: echo "repository ${{ github.repository }} "
      - run: echo "repository_owner ${{ github.repository_owner }}"
      - run: echo "event ${{ github.event.pull_request.title }}"
      - run: echo "runner ${{ runner.os }}"
      - run: echo "arch ${{ runner.arch }}"
      - run: echo "temp ${{ runner.temp }}"
      - run: echo "tool_cache ${{ runner.tool_cache }}"
      - run: echo "debug ${{ runner.debug }}"
